/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ehospital;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Alexy jr
 */
public class EHospital extends javax.swing.JFrame {

    /**
     * Creates new form EHospital
     */
    public EHospital() {
        initComponents();

        setLocationRelativeTo(this);
    }

    public void ActualizarComplejos() {
        jcb_ambulancias_complejo.removeAllItems();
        jcb_paramedicos_complejos.removeAllItems();
        jcb_ch_eliminar.removeAllItems();

        for (int i = 0; i < Complejos.size(); i++) {
            jcb_ambulancias_complejo.addItem(Complejos.get(i));
            jcb_paramedicos_complejos.addItem(Complejos.get(i));
            jcb_ch_eliminar.addItem(Complejos.get(i));
        }
    }

    public void ActualizarParamedicos() {
        jcb_paramedicos_eliminar_transferir.removeAllItems();

        for (int i = 0; i < Paramedicos.size(); i++) {
            jcb_paramedicos_eliminar_transferir.addItem(Paramedicos.get(i));
        }
    }

    public void ActualizarAmbulancias() {
        jcb_ambulancias_eliminar_transferir.removeAllItems();

        for (int i = 0; i < Ambulancias.size(); i++) {
            jcb_ambulancias_eliminar_transferir.addItem(Ambulancias.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtf_ch_nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        js_ch_cap_paramedicos = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        js_ch_cap_ambulancias = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jcb_ch_ranking_emergencias = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_ch_direccion_complejo = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jtf_paramedicos_nombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtf_paramedicos_edad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtf_paramedicos_ID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jcb_paramedicos_ranking = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jcb_paramedicos_complejos = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jtf_ambulancias_numero_placa = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtf_ambulancias_año = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtf_ambulancias_velocidad = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jcb_ambulancias_complejo = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jcb_paramedicos_eliminar_transferir = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jcb_ch_eliminar = new javax.swing.JComboBox();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jcb_ambulancias_eliminar_transferir = new javax.swing.JComboBox();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("eHospital ©");

        jLabel1.setText("Nombre del complejo");

        jLabel2.setText("Capacidad de paramedicos");

        js_ch_cap_paramedicos.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        jLabel3.setText("Capacidad de ambulancias");

        js_ch_cap_ambulancias.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        jLabel4.setText("Ranking de emergencias a tratar");

        jcb_ch_ranking_emergencias.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D" }));

        jLabel5.setText("Direccion del complejo");

        jta_ch_direccion_complejo.setColumns(20);
        jta_ch_direccion_complejo.setRows(5);
        jScrollPane1.setViewportView(jta_ch_direccion_complejo);

        jButton1.setText("Construir complejo");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcb_ch_ranking_emergencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_ch_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(js_ch_cap_ambulancias, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(js_ch_cap_paramedicos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtf_ch_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(js_ch_cap_paramedicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(js_ch_cap_ambulancias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcb_ch_ranking_emergencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jTabbedPane1.addTab("Complejos Hospitalarios", jPanel1);

        jLabel6.setText("Nombre completo");

        jLabel7.setText("Edad");

        jLabel8.setText("ID");

        jLabel9.setText("Ranking de paramedico");

        jcb_paramedicos_ranking.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D" }));

        jLabel10.setText("Complejo asignado");

        jButton2.setText("Registrar paramedico");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcb_paramedicos_ranking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_paramedicos_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_paramedicos_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_paramedicos_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcb_paramedicos_complejos, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtf_paramedicos_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtf_paramedicos_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_paramedicos_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jcb_paramedicos_ranking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jcb_paramedicos_complejos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        jTabbedPane1.addTab("Paramedicos", jPanel2);

        jLabel11.setText("Numero de placa");

        jLabel12.setText("Año del vehiculo");

        jLabel13.setText("Velocidad maxima");

        jLabel14.setText("Km/h");

        jLabel15.setText("Complejo asignado");

        jButton3.setText("Registrar ambulancia");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(jcb_ambulancias_complejo, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jtf_ambulancias_numero_placa)
                                        .addComponent(jtf_ambulancias_año, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jtf_ambulancias_velocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel14))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtf_ambulancias_numero_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jtf_ambulancias_año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jtf_ambulancias_velocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(58, 58, 58)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jcb_ambulancias_complejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        jTabbedPane1.addTab("Ambulancias", jPanel3);

        jButton4.setText("Despedir paramedico");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setText("Eliminar complejo hospitalario");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setText("Transferir");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jButton7.setText("Eliminar ambulancia");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton8.setText("Transferir");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6))
                            .addComponent(jcb_paramedicos_eliminar_transferir, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcb_ch_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton7)
                                .addGap(18, 18, 18)
                                .addComponent(jButton8))
                            .addComponent(jcb_ambulancias_eliminar_transferir, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcb_ch_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_paramedicos_eliminar_transferir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_ambulancias_eliminar_transferir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(183, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Transferencias/Despidos", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Mapa", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        boolean Campos_llenos = true;
        if ("".equals(jtf_ch_nombre.getText()) || "".equals(jta_ch_direccion_complejo.getText())) {
            Campos_llenos = false;
        }

        if (Campos_llenos) {
            String Nombre, Direccion, Ranking;
            int Capacidad_paramedicos, Capacidad_ambulancias;

            Nombre = jtf_ch_nombre.getText();
            Direccion = jta_ch_direccion_complejo.getText();
            Ranking = jcb_ch_ranking_emergencias.getSelectedItem().toString();
            Capacidad_paramedicos = (int) js_ch_cap_paramedicos.getValue();
            Capacidad_ambulancias = (int) js_ch_cap_ambulancias.getValue();

            ComplejoHospitalario Nuevo_complejo = new ComplejoHospitalario(Nombre, Direccion, Capacidad_paramedicos, Capacidad_ambulancias, Ranking);

            jcb_ambulancias_complejo.addItem(Nuevo_complejo);
            jcb_ch_eliminar.addItem(Nuevo_complejo);
            jcb_paramedicos_complejos.addItem(Nuevo_complejo);
            Complejos.add(Nuevo_complejo);

            jtf_ch_nombre.setText("");
            jta_ch_direccion_complejo.setText("");
            js_ch_cap_paramedicos.setValue(0);
            js_ch_cap_ambulancias.setValue(0);

            JOptionPane.showMessageDialog(this, "Has construido un complejo hospitalario",
                    "OPERACION EXITOSA", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Porfavor llena todos los campos",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        boolean Campos_llenos = true;
        if ("".equals(jtf_paramedicos_nombre.getText()) || "".equals(jtf_paramedicos_edad.getText())
                || "".equals(jtf_paramedicos_ID.getText()) || jcb_paramedicos_complejos.getItemCount() == 0) {
            Campos_llenos = false;
        }

        if (Campos_llenos) {
            String Nombre, Ranking, Complejo_asignado;
            int Edad, ID;

            Nombre = jtf_paramedicos_nombre.getText();
            Ranking = jcb_paramedicos_ranking.getSelectedItem().toString();
            Complejo_asignado = ((ComplejoHospitalario) jcb_paramedicos_complejos.getSelectedItem()).getNombre();
            Edad = Integer.parseInt(jtf_paramedicos_edad.getText());
            ID = Integer.parseInt(jtf_paramedicos_ID.getText());

            Paramedico Nuevo_paramedico = new Paramedico(Nombre, Edad, ID, Ranking, Complejo_asignado);

            jcb_paramedicos_eliminar_transferir.addItem(Nuevo_paramedico);
            Paramedicos.add(Nuevo_paramedico);
            for (int i = 0; i < Complejos.size(); i++) {
                if (Complejos.get(i).getNombre().equals(Complejo_asignado)) {
                    Complejos.get(i).getParamedicos().add(Nuevo_paramedico);
                }
            }
            ActualizarComplejos();

            jtf_paramedicos_nombre.setText("");
            jtf_paramedicos_edad.setText("");
            jtf_paramedicos_ID.setText("");

            JOptionPane.showMessageDialog(this, "Has contratado a un paramedico",
                    "OPERACION EXITOSA", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Detectamos campos vacios",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        boolean Campos_llenos = true;
        if ("".equals(jtf_ambulancias_numero_placa.getText()) || "".equals(jtf_ambulancias_año.getText())
                || "".equals(jtf_ambulancias_velocidad.getText()) || jcb_ambulancias_complejo.getItemCount() == 0) {
            Campos_llenos = false;
        }

        if (Campos_llenos) {
            String Numero_placa, Complejo_asignado;
            int Año_vehiculo, Velocidad_max;

            Numero_placa = jtf_ambulancias_numero_placa.getText();
            Complejo_asignado = ((ComplejoHospitalario) jcb_ambulancias_complejo.getSelectedItem()).getNombre();
            Año_vehiculo = Integer.parseInt(jtf_ambulancias_año.getText());
            Velocidad_max = Integer.parseInt(jtf_ambulancias_velocidad.getText());

            Ambulancia Nueva_ambulancia = new Ambulancia(Numero_placa, Año_vehiculo, Velocidad_max, Complejo_asignado);

            jcb_ambulancias_eliminar_transferir.addItem(Nueva_ambulancia);
            Ambulancias.add(Nueva_ambulancia);
            for (int i = 0; i < Complejos.size(); i++) {
                if (Complejos.get(i).getNombre().equals(Complejo_asignado)) {
                    Complejos.get(i).getAmbulancias().add(Nueva_ambulancia);
                }
            }
            ActualizarComplejos();

            jtf_ambulancias_numero_placa.setText("");
            jtf_ambulancias_año.setText("");
            jtf_ambulancias_velocidad.setText("");

            JOptionPane.showMessageDialog(this, "Has registrado una ambulancia",
                    "OPERACION EXITOSA", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Detectamos campos vacios",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        boolean Campos_llenos = true;
        if (jcb_ch_eliminar.getItemCount() == 0) {
            Campos_llenos = false;
        }

        if (Campos_llenos) {
            String Nombre_complejo;
            Nombre_complejo = ((ComplejoHospitalario) jcb_ch_eliminar.getSelectedItem()).getNombre();

            for (int i = 0; i < Complejos.size(); i++) {
                if (Complejos.get(i).getNombre().equals(Nombre_complejo)) {
                    Complejos.remove(i);
                }
            }

            for (int i = 0; i < Paramedicos.size(); i++) {
                if (Paramedicos.get(i).getComplejo_asignado().equals(Nombre_complejo)) {
                    Paramedicos.get(i).setComplejo_asignado("");
                }
            }

            for (int i = 0; i < Ambulancias.size(); i++) {
                if (Ambulancias.get(i).getComplejo_asignado().equals(Nombre_complejo)) {
                    Ambulancias.get(i).setComplejo_asignado("");
                }
            }

            ActualizarComplejos();
            ActualizarParamedicos();
            ActualizarAmbulancias();

            JOptionPane.showMessageDialog(this, "Ha eliminado un complejo hospitalario",
                    "OPERACION EXITOSA", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Detectamos campos vacios",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        boolean Campos_llenos = true;

        if (jcb_paramedicos_eliminar_transferir.getItemCount() == 0) {
            Campos_llenos = false;
        }

        if (Campos_llenos) {
            String Nombre_paramedico;

            Nombre_paramedico = ((Paramedico) jcb_paramedicos_eliminar_transferir.getSelectedItem()).getNombre();

            for (int i = 0; i < Paramedicos.size(); i++) {
                Paramedicos.remove(jcb_paramedicos_eliminar_transferir.getSelectedIndex());
            }

            for (int i = 0; i < Complejos.size(); i++) {
                for (int j = 0; j < Complejos.get(i).getParamedicos().size(); j++) {
                    if (Complejos.get(i).getParamedicos().get(j).getNombre().equals(Nombre_paramedico)) {
                        Complejos.get(i).getParamedicos().remove(j);
                    }
                }
            }

            ActualizarComplejos();
            ActualizarParamedicos();

            JOptionPane.showMessageDialog(this, "Ha eliminado un paramedico",
                    "OPERACION EXITOSA", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Hemos detectado campos vacios",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        boolean Campos_llenos = true;

        if (jcb_paramedicos_eliminar_transferir.getItemCount() == 0 || jcb_ch_eliminar.getItemCount() == 0) {
            Campos_llenos = false;
        }

        if (Campos_llenos) {
            String Nombre_complejo, Nombre_paramedico;

            Nombre_complejo = ((ComplejoHospitalario) jcb_ch_eliminar.getSelectedItem()).getNombre();
            Nombre_paramedico = ((Paramedico) jcb_paramedicos_eliminar_transferir.getSelectedItem()).getNombre();
            Paramedico Paramedico_transferir = (Paramedico) jcb_paramedicos_eliminar_transferir.getSelectedItem();

            for (int i = 0; i < Complejos.size(); i++) {
                for (int j = 0; j < Complejos.get(i).getParamedicos().size(); j++) {
                    if (Complejos.get(i).getParamedicos().get(j).getNombre().equals(Nombre_paramedico)) {
                        Complejos.get(i).getParamedicos().remove(j);
                    }
                }
            }

            for (int i = 0; i < Complejos.size(); i++) {
                if (Complejos.get(i).getNombre().equals(Nombre_complejo)) {
                    for (int j = 0; j < Complejos.get(i).getParamedicos().size(); j++) {
                        Complejos.get(i).getParamedicos().add(Paramedico_transferir);
                    }
                }
            }

            for (int i = 0; i < Paramedicos.size(); i++) {
                if (Paramedicos.get(i).getNombre().equals(Nombre_paramedico)) {
                    Paramedicos.get(i).setComplejo_asignado(Nombre_complejo);
                }
            }

            ActualizarComplejos();
            ActualizarParamedicos();

            JOptionPane.showMessageDialog(this, "Ha trasnferido un paramedico",
                    "OPERACION EXITOSA", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Hemos detectado campos vacios",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        boolean Campos_llenos = true;

        if (jcb_ambulancias_eliminar_transferir.getItemCount() == 0) {
            Campos_llenos = false;
        }

        if (Campos_llenos) {
            String Numero_ambulancia;

            Numero_ambulancia = ((Ambulancia) jcb_ambulancias_eliminar_transferir.getSelectedItem()).getNumero_placa();

            for (int i = 0; i < Ambulancias.size(); i++) {
                if (Ambulancias.get(i).getNumero_placa().equals(Numero_ambulancia)) {
                    Ambulancias.remove(i);
                }
            }

            for (int i = 0; i < Complejos.size(); i++) {
                for (int j = 0; j < Complejos.get(i).getAmbulancias().size(); j++) {
                    if (Complejos.get(i).getAmbulancias().get(j).getNumero_placa().equals(Numero_ambulancia)) {
                        Complejos.get(i).getAmbulancias().remove(j);
                    }
                }
            }

            JOptionPane.showMessageDialog(this, "Ha eliminado una ambulancia",
                    "OPERACION EXITOSA", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Hemos detectado campos vacios",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        boolean Campos_llenos = true;

        if (jcb_ambulancias_eliminar_transferir.getItemCount() == 0 || jcb_ch_eliminar.getItemCount() == 0) {
            Campos_llenos = false;
        }

        if (Campos_llenos) {
            String Nombre_complejo, Numero_ambulancia;

            Nombre_complejo = ((ComplejoHospitalario) jcb_ch_eliminar.getSelectedItem()).getNombre();
            Numero_ambulancia = ((Ambulancia) jcb_ambulancias_eliminar_transferir.getSelectedItem()).getNumero_placa();
            Ambulancia Ambulancia_transferir = (Ambulancia) jcb_ambulancias_eliminar_transferir.getSelectedItem();

            for (int i = 0; i < Complejos.size(); i++) {
                for (int j = 0; j < Complejos.get(i).getAmbulancias().size(); j++) {
                    if (Complejos.get(i).getAmbulancias().get(j).getNumero_placa().equals(Numero_ambulancia)) {
                        Complejos.get(i).getAmbulancias().remove(j);
                    }
                }
            }

            for (int i = 0; i < Complejos.size(); i++) {
                if (Complejos.get(i).getNombre().equals(Nombre_complejo)) {
                    Complejos.get(i).getAmbulancias().add(Ambulancia_transferir);
                }
            }

            for (int i = 0; i < Ambulancias.size(); i++) {
                if (Ambulancias.get(i).getNumero_placa().equals(Numero_ambulancia)) {
                    Ambulancias.get(i).setComplejo_asignado(Nombre_complejo);
                }
            }

            ActualizarAmbulancias();
            ActualizarComplejos();

            JOptionPane.showMessageDialog(this, "Ha trasnferido una ambulancia",
                    "OPERACION EXITOSA", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Hemos detectado campos vacios",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EHospital().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox jcb_ambulancias_complejo;
    private javax.swing.JComboBox jcb_ambulancias_eliminar_transferir;
    private javax.swing.JComboBox jcb_ch_eliminar;
    private javax.swing.JComboBox jcb_ch_ranking_emergencias;
    private javax.swing.JComboBox jcb_paramedicos_complejos;
    private javax.swing.JComboBox jcb_paramedicos_eliminar_transferir;
    private javax.swing.JComboBox jcb_paramedicos_ranking;
    private javax.swing.JSpinner js_ch_cap_ambulancias;
    private javax.swing.JSpinner js_ch_cap_paramedicos;
    private javax.swing.JTextArea jta_ch_direccion_complejo;
    private javax.swing.JTextField jtf_ambulancias_año;
    private javax.swing.JTextField jtf_ambulancias_numero_placa;
    private javax.swing.JTextField jtf_ambulancias_velocidad;
    private javax.swing.JTextField jtf_ch_nombre;
    private javax.swing.JTextField jtf_paramedicos_ID;
    private javax.swing.JTextField jtf_paramedicos_edad;
    private javax.swing.JTextField jtf_paramedicos_nombre;
    // End of variables declaration//GEN-END:variables
ArrayList<ComplejoHospitalario> Complejos = new ArrayList();
    ArrayList<Paramedico> Paramedicos = new ArrayList();
    ArrayList<Ambulancia> Ambulancias = new ArrayList();
}
